### ISSUE TITLE
Crash On Startup With Respawn Obelisks.

### ISSUE THREAD

**Issue by CraftyZombie** [Insane-96/IguanaTweaksReborn#261]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**: 
* Minecraft:  1.20.1
* Forge: 47.2.19
* IguanaTweaks Reborn: 3.0.4-mc1.20.1
* InsaneLib: 1.12.1

**What Happens**:  
Explain what's the problem
The game crashes on startup.
//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
https://gist.github.com/CraftyZombie/eb10f481233ffe10e9646d861e5362c9
(This is latest.log and debug.log. No crash report generates.)

//If different from default
**Config**:  
Config is default, this is a new installation.

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes.

Here are the other mods:
Architectury 9.1.12
MaxHealthFix 12.0.2
Resourceful Config 2.1.2
Respawn Obelisks 2.4-c

**Comment by CraftyZombie** [comment]
For some reason, I realize those logs may not contain the error in them.

Here it is:

```
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.module.ResolutionException: Module iguanatweaksreborn contains package com.ezylang.evalex.functions.basic, module EvalEx exports package com.ezylang.evalex.functions.basic to iguanatweaksreborn
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:807)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 8 more
Exiting with ERROR
```

**Comment by Insane96** [comment]
Seems to be resolved through Discord

**Comment by CraftyZombie** [comment]
I'm a little confused. What happened?

Is it an issue on Respawn Obelisk's end?

To be clear I'm talking about the mod, not the feature from IguanaTweaks Expanded.

**Comment by CraftyZombie** [comment]
https://github.com/RedPxnda/RespawnObelisks/issues/11#issuecomment-1890808958
https://github.com/RedPxnda/RespawnObelisks/issues/11#issuecomment-1890807267
